"""add role column in admin_master table

Revision ID: 38278daf0594
Revises: ad8b26d4dffd
Create Date: 2026-02-10 16:07:59.529387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38278daf0594'
down_revision = 'ad8b26d4dffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_master', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
