"""create admin_master table

Revision ID: 671db63f0e90
Revises: 1ac97b623f70
Create Date: 2026-02-09 19:14:41.265246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671db63f0e90'
down_revision = '1ac97b623f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_master')
    # ### end Alembic commands ###
